-timescale 1ns/1ns
-uvmhome $UVM_HOME
-f bathtub_vip.f
-incdir $BATHTUB_VIP_DIR/test/resources/sequences/mock_sequence_item/mock_sequence
-incdir $BATHTUB_VIP_DIR/test/resources/sequences/mock_sequence_item
-incdir $BATHTUB_VIP_DIR/test/resources/sequences/virtual
